// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnvBiz8rhIHmF9t44tzye4Q3TkQqao6ys',
    appId: '1:481756200926:web:033e1f016ab784f113e74f',
    messagingSenderId: '481756200926',
    projectId: 'ayurspace-app',
    authDomain: 'ayurspace-app.firebaseapp.com',
    storageBucket: 'ayurspace-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8qi57yFSo_gdkF473G-_wRgbl8ITtpT4',
    appId: '1:481756200926:android:b180613bcf15cf9313e74f',
    messagingSenderId: '481756200926',
    projectId: 'ayurspace-app',
    storageBucket: 'ayurspace-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyh_t7lKkqfNp9fqICWjXS_Xx5f3432Ss',
    appId: '1:481756200926:ios:3431f53fac20bd7d13e74f',
    messagingSenderId: '481756200926',
    projectId: 'ayurspace-app',
    storageBucket: 'ayurspace-app.firebasestorage.app',
    iosBundleId: 'com.ayurspace.ayurspaceFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyh_t7lKkqfNp9fqICWjXS_Xx5f3432Ss',
    appId: '1:481756200926:ios:3431f53fac20bd7d13e74f',
    messagingSenderId: '481756200926',
    projectId: 'ayurspace-app',
    storageBucket: 'ayurspace-app.firebasestorage.app',
    iosBundleId: 'com.ayurspace.ayurspaceFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnvBiz8rhIHmF9t44tzye4Q3TkQqao6ys',
    appId: '1:481756200926:web:2e7c124fb8f997bb13e74f',
    messagingSenderId: '481756200926',
    projectId: 'ayurspace-app',
    authDomain: 'ayurspace-app.firebaseapp.com',
    storageBucket: 'ayurspace-app.firebasestorage.app',
  );
}
